# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/nokia/sdm660-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter DRG PL2,$(TARGET_DEVICE)),)

endif
