# Copyright (C) 2019-2020 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/nokia/PL2/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/nokia/PL2

PRODUCT_COPY_FILES += \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/front/ISO640_1280x720.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/front/ISO640_1280x720.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/front/ISO640_2048x1536.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/front/ISO640_2048x1536.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/front/ISO640_2592x1944.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/front/ISO640_2592x1944.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/front/ISO640_2688x1512.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/front/ISO640_2688x1512.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/front/ISO640_3264x2448.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/front/ISO640_3264x2448.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/front/ISO640_864x480.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/front/ISO640_864x480.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/front/ISO800_1280x720.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/front/ISO800_1280x720.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/front/ISO800_2048x1536.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/front/ISO800_2048x1536.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/front/ISO800_2592x1944.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/front/ISO800_2592x1944.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/front/ISO800_2688x1512.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/front/ISO800_2688x1512.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/front/ISO800_3264x2448.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/front/ISO800_3264x2448.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/front/ISO800_864x480.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/front/ISO800_864x480.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/rear/ISO640_1280x720.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/rear/ISO640_1280x720.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/rear/ISO640_2048x1536.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/rear/ISO640_2048x1536.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/rear/ISO640_2688x1512.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/rear/ISO640_2688x1512.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/rear/ISO640_3200x2400.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/rear/ISO640_3200x2400.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/rear/ISO640_3840x2160.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/rear/ISO640_3840x2160.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/rear/ISO640_4608x3456.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/rear/ISO640_4608x3456.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/rear/ISO800_1280x720.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/rear/ISO800_1280x720.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/rear/ISO800_2048x1536.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/rear/ISO800_2048x1536.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/rear/ISO800_2688x1512.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/rear/ISO800_2688x1512.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/rear/ISO800_3200x2400.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/rear/ISO800_3200x2400.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/rear/ISO800_3840x2160.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/rear/ISO800_3840x2160.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/PL2/ncf/rear/ISO800_4608x3456.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/PL2/ncf/rear/ISO800_4608x3456.ncf \
    vendor/nokia/PL2/proprietary/vendor/etc/acdbdata/PL2/sdm660-snd-card-pl2/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/PL2/sdm660-snd-card-pl2/Bluetooth_cal.acdb \
    vendor/nokia/PL2/proprietary/vendor/etc/acdbdata/PL2/sdm660-snd-card-pl2/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/PL2/sdm660-snd-card-pl2/General_cal.acdb \
    vendor/nokia/PL2/proprietary/vendor/etc/acdbdata/PL2/sdm660-snd-card-pl2/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/PL2/sdm660-snd-card-pl2/Global_cal.acdb \
    vendor/nokia/PL2/proprietary/vendor/etc/acdbdata/PL2/sdm660-snd-card-pl2/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/PL2/sdm660-snd-card-pl2/Handset_cal.acdb \
    vendor/nokia/PL2/proprietary/vendor/etc/acdbdata/PL2/sdm660-snd-card-pl2/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/PL2/sdm660-snd-card-pl2/Hdmi_cal.acdb \
    vendor/nokia/PL2/proprietary/vendor/etc/acdbdata/PL2/sdm660-snd-card-pl2/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/PL2/sdm660-snd-card-pl2/Headset_cal.acdb \
    vendor/nokia/PL2/proprietary/vendor/etc/acdbdata/PL2/sdm660-snd-card-pl2/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/PL2/sdm660-snd-card-pl2/Speaker_cal.acdb \
    vendor/nokia/PL2/proprietary/vendor/etc/audio_platform_info_pl2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_platform_info_pl2.xml \
    vendor/nokia/PL2/proprietary/vendor/etc/audio_platform_info_pl2_cn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_platform_info_pl2_cn.xml \
    vendor/nokia/PL2/proprietary/vendor/etc/mixer_paths_pl2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_paths_pl2.xml \
    vendor/nokia/PL2/proprietary/vendor/etc/mixer_paths_pl2_cn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_paths_pl2_cn.xml \
    vendor/nokia/PL2/proprietary/vendor/etc/sensors/sensor_def_qcomdev_pl2.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sensor_def_qcomdev_pl2.conf \
    vendor/nokia/PL2/proprietary/vendor/etc/thermal-engine-PL2.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-PL2.conf
